version: '3.8'

services:
  service_auth:
    build: ./Service_Auth
    ports:
      - "5000:5000"
    volumes:
      - ./Service_Auth:/app
    working_dir: /app

  service_eon:
    build: ./Service_EON
    ports:
      - "5001:5001"
    volumes:
      - ./Service_EON:/app
    working_dir: /app
    depends_on:
      - service_auth
